Support for local public suffix file
dovahcrow/tldextract-rs pull request #14
Opened 2023-10-09 23:05 UTC by daareiza

This PR adds the ability to use a locally stored public suffix file (instead of a cached one) due to some use cases that I have, I think this will also solve #8 

Also, there are some cargo clippy/fmt cleanups and `idna` crate update

2023-10-09 23:06 UTC, daareiza commented on src/cache/mod.rs
> +#[cfg(not(feature = "remote"))]
Without this the lib doesn't compiles due to duplicated `get_tld_cache` fn when `remote` feature is enabled

2023-10-11 02:41 UTC, dovahcrow requested changes
I left one comment in the code. Also, can you add a test so that 1. verify the read local functionality, and 2. guide others to create the local file?

Thanks!

2023-10-11 02:41 UTC, dovahcrow commented on src/cache/mod.rs
> +    T: Into<Option<String>>,
Why is this into string?

2023-10-11 02:41 UTC, dovahcrow commented on src/cache/mod.rs
> +#[cfg(not(feature = "remote"))]
Right. Why did I forget to add that...

2023-10-18 18:14 UTC, daareiza commented on src/cache/mod.rs
> +    T: Into<Option<String>>,
This is to avoid having to do any pre-processing to the original `TldOption` value, I didn't see it necessary, although if there is any issue with that we can just change it to keep consistency

2024-01-23 19:05 UTC, daareiza commented
@dovahcrow hi 😃, do you have any more thoughts with regards this change?

2024-01-23 19:19 UTC, dovahcrow approved these changes

2024-01-23 19:19 UTC, merged